name: ShiftLeft Analysis

on:
  pull_request:
  workflow_dispatch:

env:
  SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
  
jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Download ShiftLeft CLI
      run: curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Build JAR
      run: mvn clean install

    - name: Perform Analysis
      run: |
        export SCANID=$(./sl analyze --java --app HSLgithub --cpg --tag \
        branch=${{ github.head_ref || steps.extract_branch.outputs.branch }} \
        --wait target/hello-shiftleft-0.0.1.jar)
        echo "SCANID=8" >> $GITHUB_ENV

    - name: Check Application Security Stance
      run: |
        ./sl check-analysis --app HSLgithub --verbose --target scan.${{env.SCANID}}
        
        
